### ISSUE TITLE
Fields of ExecutorSettings must have a help string

### ISSUE THREAD

**Issue by Ulthran** [snakemake/snakemake-executor-plugin-aws-batch#4]
When I try to use this executor I get:

```
Error: Error loading Snakemake plugin aws-batch: Fields of ExecutorSettings must have a help string. (field: Field(name='fsap_id',type=typing.Optional[str],default=(Field(name=None,type=None,default=None,default_factory=<dataclasses._MISSING_TYPE object at 0x7f97588dbda0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({'help': 'The fsap id of the EFS instance you want to use that is shared with your local environment', 'env_var': False, 'required': False}),kw_only=<dataclasses._MISSING_TYPE object at 0x7f97588dbda0>,_field_type=None),),default_factory=<dataclasses._MISSING_TYPE object at 0x7f97588dbda0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=False,_field_type=_FIELD))
```

When I remove the EFS fields from ExecutorSettings and fix type hints on the others, I run into this error:

```
Traceback (most recent call last):

  File "/home/ec2-user/miniconda3/envs/sunbeam/lib/python3.12/site-packages/snakemake/cli.py", line 2055, in args_to_api
    dag_api.execute_workflow(

  File "/home/ec2-user/miniconda3/envs/sunbeam/lib/python3.12/site-packages/snakemake/api.py", line 589, in execute_workflow
    workflow.execute(

  File "/home/ec2-user/miniconda3/envs/sunbeam/lib/python3.12/site-packages/snakemake/workflow.py", line 1143, in execute
    self.upload_sources()

  File "/home/ec2-user/miniconda3/envs/sunbeam/lib/python3.12/site-packages/snakemake/workflow.py", line 273, in upload_sources
    self.write_source_archive(Path(f.name))

  File "/home/ec2-user/miniconda3/envs/sunbeam/lib/python3.12/site-packages/snakemake/workflow.py", line 317, in write_source_archive
    for f in get_files():

  File "/home/ec2-user/miniconda3/envs/sunbeam/lib/python3.12/site-packages/snakemake/workflow.py", line 293, in get_files
    if f.startswith(".."):
       ^^^^^^^^^^^^

AttributeError: 'PosixPath' object has no attribute 'startswith'
```

At this point it's not clear to me what's going wrong. What's the state of development for this plugin? Is there any progress on getting this picked up by AWS?

**Comment by akhil-elucidata** [comment]
I'd looking in to this as well rn. Would be really helpful to know if there's any update on this plugin!
